apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-app-dev
namePrefix: dev-
commonLabels:
  env: dev
images:
- name: gitops-app
  newName: dockerlecture/gitops-app
  newTag: sha-8d6377b

replicas:
- count: 1
  name: gitops-app
